name: Build & Deploy
on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy Ghost Theme
      uses: TryGhost/action-deploy-theme@v1.3.1
      with:
        api-url: https://nussel.io
        api-key: 5f3f374a4180d9476963e014:a0bc7214c4cc3bd8a0de6281f48be80b887a4d4af0226f644d6aa8c0f3a909fc
    
